#!/usr/bin/env bash
# Display listening ports, PID and program name

echo "Listening Ports, PID and Program Name:"
echo "Port  PID   Program"

# Use the 'lsof' command to list open files and their associated processes
# -i specifies to list Internet sockets
# -P to avoid resolving host names
# -n to avoid resolving port names
# -sTCP:LISTEN to show only listening TCP sockets

lsof -i -P -n -sTCP:LISTEN | awk '{print $9, $2, $1}' | column -t
