#!/usr/bin/env bash
# This is Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.

# Iterate through all the process IDs
for pid in $(ls /proc | grep -E '[0-9]+')
do
	# Get the process name from the /proc/<pid>/comm file
	process_name=$(cat /proc/ $pid /comm)
	# Check if the process name contains the word "bash"
	if [[ $process_name == *"bash"* ]]
	then
		# Display the PID and process name if it does
		echo "PID: $pid, Process Name: $process_name"
	fi
done
