#!/usr/bin/env bash
# manage_my_process script

case "$1" in
	start)
		# Start the process and create a PID file
		nohup bash -c "while true; do echo I am alive! >> /tmp/my_process; sleep 2; done" &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		# Stop the process and remove the PID file
		kill $(cat /var/run/my_process.pid)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		# Stop the process, remove the PID file, start the process and create a new PID file
		kill $(cat /var/run/my_process.pid)
		rm /var/run/my_process.pid
		nohup bash -c "while true; do echo I am alive! >> /tmp/my_process; sleep 2; done" &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
	# Display usage if any other argument or no argument is passed
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac	
