#!/usr/bin/env bash
#This is a Bash script that displays the content of the file /etc/passwd.

while read -r line;
do
	# Extract username, user id, and home directory path
	username=$(echo $line | awk -F: '{print $1}')
	userid=$(echo $line | awk -F: '{print $3}')
	homedir=$(echo $line | awk -F: '{print $6}')

	# Display the extracted information
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"
done < /etc/passwd
