#!/usr/bin/env bash
# Script to display content of /etc/passwd file

IFS=:
while read -r username group_id userid home_directory command shell password user_id_info;
do
	# Display the extracted information
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command/$shell."
	echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
