#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes:
hours=0
minutes=1

while [ $hours -le 12 ];
do
	while [ $minutes -le 59 ];
	do
		echo "$hours : $minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
	minutes=0
done | head -n 70
