#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
file_h="School"

if [ -e "$file_h" ]
then

    echo "School file exists"
    if [ -s "$file_h" ]
    then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
